# Generated by Django 5.2 on 2025-11-09 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_department_level_delete_course'),
        ('departments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_levels', to='academics.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='students', to='departments.department'),
        ),
    ]
