# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0004_simpleuser_first_name_simpleuser_last_name"),
        ("departments", "0001_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisees",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="departments.department"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.level",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.simpleuser"
            ),
        ),
    ]
