# Generated by Django 5.2.8 on 2025-12-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseAttendance",
        ),
    ]
