# Generated by Django 5.2 on 2025-11-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_email'),
        ('teachers', '0004_alter_teacher_options_alter_teacher_google_scholar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
