# Generated by Django 5.2 on 2025-11-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_level_code_level_number_alter_level_name'),
        ('students', '0005_student_user_courseattendance_and_more'),
        ('teachers', '0004_alter_teacher_options_alter_teacher_google_scholar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.level'),
        ),
    ]
