# Generated by Django 5.2.7 on 2025-12-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="dean_name",
        ),
    ]
