# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_students", models.PositiveIntegerField()),
                ("total_teachers", models.PositiveIntegerField()),
                ("average_gpa", models.DecimalField(decimal_places=2, max_digits=3)),
                ("semester", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacultySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_students_per_class", models.PositiveIntegerField(default=30)),
                ("max_courses_per_student", models.PositiveIntegerField(default=8)),
                ("grading_system", models.CharField(default="AA-FF", max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dean",
                        to="faculty.faculty",
                    ),
                ),
            ],
        ),
    ]
