# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dean", "0001_initial"),
        ("faculty", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dean",
            name="teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dean_role",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="facultyreport",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faculty.faculty"
            ),
        ),
        migrations.AddField(
            model_name="facultysettings",
            name="faculty",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="faculty.faculty"
            ),
        ),
    ]
