# Generated by Django 5.2 on 2025-11-09 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dean', '0001_initial'),
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
        ('teachers', '0002_rename_name_teacher_full_name_remove_teacher_e_mail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dean',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dean_users', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='dean',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dean.dean'),
        ),
        migrations.AddField(
            model_name='departmentheadapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dean.dean'),
        ),
        migrations.AddField(
            model_name='departmentheadapproval',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AddField(
            model_name='departmentheadapproval',
            name='new_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='facultyreport',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='facultysettings',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
    ]
