# Generated by Django 5.2 on 2025-11-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_simpleuser_password_alter_simpleuser_role'),
        ('dean', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dean',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.simpleuser'),
        ),
    ]
