# Generated by Django 5.2 on 2025-11-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0003_alter_dean_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentheadapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='departmentheadapproval',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentheadapproval',
            name='new_head',
        ),
        migrations.DeleteModel(
            name='CourseApproval',
        ),
        migrations.DeleteModel(
            name='DepartmentHeadApproval',
        ),
    ]
