# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_simpleuser_first_name_simpleuser_last_name"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterGradeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=2, unique=True)),
                ("min_score", models.FloatField()),
                ("max_score", models.FloatField()),
                ("gpa_value", models.FloatField(help_text="4.0 sistemi katsayısı")),
            ],
            options={
                "ordering": ["-gpa_value"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField(blank=True, null=True)),
                ("letter_grade", models.CharField(blank=True, max_length=2, null=True)),
                ("gpa_value", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="courses.courseoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="accounts.simpleuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not",
                "verbose_name_plural": "Notlar",
                "unique_together": {("student", "offering")},
            },
        ),
        migrations.CreateModel(
            name="GradeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseassessmentcomponent",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_grades",
                        to="grades.grade",
                    ),
                ),
            ],
            options={
                "unique_together": {("grade", "component")},
            },
        ),
    ]
