# Generated by Django 5.2 on 2025-11-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courseassessmentcomponent_options'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='final',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='makeup',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='midterm',
        ),
        migrations.AlterUniqueTogether(
            name='gradecomponent',
            unique_together={('grade', 'component')},
        ),
    ]
