# Generated by Django 5.2.7 on 2025-10-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Öğrenci"),
                    ("TEACHER", "Öğretmen"),
                    ("HOD", "Bölüm Başkanı"),
                    ("DEAN", "Dekan"),
                ],
                max_length=20,
            ),
        ),
    ]
