# Generated by Django 5.2 on 2025-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_simpleuser_password_alter_simpleuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
