# Generated by Django 5.2 on 2025-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_simpleuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
