# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_simpleuser_first_name_simpleuser_last_name"),
        ("courses", "0003_initial"),
        ("departments", "0001_initial"),
        ("hod", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="head",
            name="teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="head_role",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="headreportlog",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="departments.department"
            ),
        ),
        migrations.AddField(
            model_name="headreportlog",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.simpleuser",
            ),
        ),
        migrations.AddField(
            model_name="teachercourseassignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="teachercourseassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacherperformance",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="teacherperformance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teachers.teacher"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursestatistic",
            unique_together={("course", "department", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="teacherperformance",
            unique_together={("teacher", "course", "semester", "year")},
        ),
    ]
