# Generated by Django 5.2 on 2025-11-14 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_remove_department_temp_fix'),
        ('hod', '0001_initial'),
        ('teachers', '0003_alter_teacher_options_remove_teacher_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='departments.department')),
                ('teacher_profile', models.OneToOneField(blank=True, help_text='Bu kullanıcı aynı zamanda öğretim görevlisiyse atanabilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_role', to='teachers.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bölüm Başkanı',
                'verbose_name_plural': 'Bölüm Başkanları',
                'ordering': ['department'],
            },
        ),
    ]
