# Generated by Django 5.2 on 2025-11-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_simpleuser_password_alter_simpleuser_role'),
        ('hod', '0002_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='user',
        ),
        migrations.AddField(
            model_name='head',
            name='head_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='head_profile', to='accounts.simpleuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headreportlog',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.simpleuser'),
        ),
    ]
