# Generated by Django 5.2.8 on 2025-12-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0002_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="head",
            name="head_user",
        ),
        migrations.AlterField(
            model_name="head",
            name="teacher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head_role",
                to="teachers.teacher",
            ),
        ),
    ]
