# Generated by Django 5.2 on 2025-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_remove_head_user_head_head_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentStatistic',
        ),
    ]
