# Generated by Django 5.2 on 2025-11-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_programoutcome_learningoutcome_and_more'),
        ('hod', '0004_delete_departmentstatistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercourseassignment',
            options={'ordering': ['teacher', 'course'], 'verbose_name': 'Öğretmen-Ders Ataması', 'verbose_name_plural': 'Öğretmen-Ders Atamaları'},
        ),
        migrations.AlterUniqueTogether(
            name='teachercourseassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
