# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_simpleuser_first_name_simpleuser_last_name"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[
                            ("FACULTY", "Fakülte Hocası"),
                            ("DEPARTMENT", "Bölüm Hocası"),
                            ("ELECTIVE", "Seçmeli Ders Hocası"),
                        ],
                        default="DEPARTMENT",
                        max_length=20,
                        verbose_name="Öğretmen Tipi",
                    ),
                ),
                (
                    "academic_title",
                    models.CharField(
                        choices=[
                            ("PROF_DR", "Prof. Dr."),
                            ("ASSOC_PROF_DR", "Doç. Dr."),
                            ("ASSIST_PROF_DR", "Dr. Öğr. Üyesi"),
                            ("INSTRUCTOR", "Öğr. Gör."),
                            ("RESEARCH_ASSIST", "Arş. Gör."),
                        ],
                        default="INSTRUCTOR",
                        max_length=20,
                        verbose_name="Akademik Unvan",
                    ),
                ),
                (
                    "expertise_area",
                    models.TextField(blank=True, verbose_name="Uzmanlık Alanları"),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ofis No"
                    ),
                ),
                (
                    "office_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Ofis Telefonu"
                    ),
                ),
                ("personal_website", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("google_scholar", models.URLField(blank=True)),
                ("researchgate", models.URLField(blank=True)),
                ("orcid", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                        verbose_name="Bölüm",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to="accounts.simpleuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğretim Görevlisi",
                "verbose_name_plural": "Öğretim Görevlileri",
                "ordering": ["academic_title", "id"],
            },
        ),
        migrations.CreateModel(
            name="OfficeHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "Pazartesi"),
                            ("TUE", "Salı"),
                            ("WED", "Çarşamba"),
                            ("THU", "Perşembe"),
                            ("FRI", "Cuma"),
                            ("SAT", "Cumartesi"),
                            ("SUN", "Pazar"),
                        ],
                        max_length=3,
                        verbose_name="Gün",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Başlangıç Saati")),
                ("end_time", models.TimeField(verbose_name="Bitiş Saati")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_hours",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ofis Saati",
                "verbose_name_plural": "Ofis Saatleri",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "Pazartesi"),
                            ("TUE", "Salı"),
                            ("WED", "Çarşamba"),
                            ("THU", "Perşembe"),
                            ("FRI", "Cuma"),
                            ("SAT", "Cumartesi"),
                            ("SUN", "Pazar"),
                        ],
                        max_length=3,
                        verbose_name="Gün",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Başlangıç Saati")),
                ("end_time", models.TimeField(verbose_name="Bitiş Saati")),
                ("location", models.CharField(max_length=100, verbose_name="Yer")),
                (
                    "activity_type",
                    models.CharField(max_length=50, verbose_name="Etkinlik Türü"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğretmen Programı",
                "verbose_name_plural": "Öğretmen Programları",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
