# Generated by Django 5.2 on 2025-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='e_mail',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(related_name='teachers', to='departments.department'),
        ),
    ]
