# Generated by Django 5.2 on 2025-11-14 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_remove_department_temp_fix'),
        ('teachers', '0002_rename_name_teacher_full_name_remove_teacher_e_mail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['academic_title', 'user__last_name'], 'verbose_name': 'Öğretim Görevlisi', 'verbose_name_plural': 'Öğretim Görevlileri'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='academic_title',
            field=models.CharField(choices=[('PROF_DR', 'Prof. Dr.'), ('ASSOC_PROF_DR', 'Doç. Dr.'), ('ASSIST_PROF_DR', 'Dr. Öğr. Üyesi'), ('INSTRUCTOR', 'Öğr. Gör.'), ('RESEARCH_ASSIST', 'Arş. Gör.')], default='INSTRUCTOR', max_length=20, verbose_name='Akademik Unvan'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Sicil No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='expertise_area',
            field=models.TextField(blank=True, verbose_name='Uzmanlık Alanları'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='google_scholar',
            field=models.URLField(blank=True, verbose_name='Google Scholar'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profili'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ofis No'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Ofis Telefonu'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='orcid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ORCID ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='personal_website',
            field=models.URLField(blank=True, verbose_name='Kişisel Website'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='researchgate',
            field=models.URLField(blank=True, verbose_name='ResearchGate'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('FACULTY', 'Fakülte Hocası'), ('DEPARTMENT', 'Bölüm Hocası'), ('ELECTIVE', 'Seçmeli Ders Hocası')], default='DEPARTMENT', max_length=20, verbose_name='Öğretmen Tipi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Pazartesi'), ('TUE', 'Salı'), ('WED', 'Çarşamba'), ('THU', 'Perşembe'), ('FRI', 'Cuma'), ('SAT', 'Cumartesi'), ('SUN', 'Pazar')], max_length=3, verbose_name='Gün')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Ofis Saati',
                'verbose_name_plural': 'Ofis Saatleri',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Pazartesi'), ('TUE', 'Salı'), ('WED', 'Çarşamba'), ('THU', 'Perşembe'), ('FRI', 'Cuma'), ('SAT', 'Cumartesi'), ('SUN', 'Pazar')], max_length=3, verbose_name='Gün')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('location', models.CharField(max_length=100, verbose_name='Yer')),
                ('activity_type', models.CharField(max_length=50, verbose_name='Etkinlik Türü')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Öğretmen Programı',
                'verbose_name_plural': 'Öğretmen Programları',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Bölüm'),
            preserve_default=False,
        ),
    ]
