# Generated by Django 5.2 on 2025-11-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_simpleuser_password_alter_simpleuser_role'),
        ('teachers', '0003_alter_teacher_options_remove_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['academic_title', 'id'], 'verbose_name': 'Öğretim Görevlisi', 'verbose_name_plural': 'Öğretim Görevlileri'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='google_scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='orcid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='researchgate',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='accounts.simpleuser'),
        ),
    ]
