# Generated by Django 5.2.7 on 2025-12-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "teachers",
            "0004_alter_teacher_options_alter_teacher_google_scholar_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="employee_id",
        ),
    ]
