# Generated by Django 5.2.8 on 2025-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComponentLearningProgramRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_weight",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Learning Outcome Katkısı (%)"
                    ),
                ),
                (
                    "program_weight",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Program Outcome Katkısı (%)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Component – Learning & Program Outcome İlişkisi",
                "verbose_name_plural": "Component – Learning & Program Outcome İlişkileri",
                "ordering": ["component", "learning_outcome"],
            },
        ),
        migrations.CreateModel(
            name="ComponentLearningRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0, verbose_name="Etki Oranı (%)")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("credit", models.FloatField(blank=True, null=True)),
                ("ects", models.FloatField(blank=True, null=True, verbose_name="AKTS")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("POOL", "Havuz Dersi"),
                            ("FACULTY", "Fakülte Dersi"),
                            ("DEPARTMENT", "Bölüm Dersi"),
                        ],
                        max_length=20,
                        verbose_name="Ders Türü",
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Dönem"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAssessmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MIDTERM", "Vize"),
                            ("FINAL", "Final"),
                            ("ASSIGNMENT", "Ödev"),
                            ("ATTENDANCE", "Devam"),
                            ("QUIZ", "Quiz"),
                            ("PROJECT", "Proje"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["offering", "type"],
            },
        ),
        migrations.CreateModel(
            name="CourseAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="Katıldı"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Not"),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["schedule__day", "schedule__start_time"],
            },
        ),
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("resources", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("week", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="CourseGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("SPRING", "Bahar"),
                            ("FALL", "Güz"),
                            ("SUMMER", "Yaz"),
                            ("WINTER", "Kış"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("section", models.CharField(blank=True, max_length=10)),
                (
                    "max_students",
                    models.PositiveIntegerField(default=30, verbose_name="Kontenjan"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Pazartesi"),
                            ("TUE", "Salı"),
                            ("WED", "Çarşamba"),
                            ("THU", "Perşembe"),
                            ("FRI", "Cuma"),
                            ("SAT", "Cumartesi"),
                            ("SUN", "Pazar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("place", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["day", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Kayıtlı"),
                            ("WAITLISTED", "Yedek"),
                            ("DROPPED", "Bırakıldı"),
                            ("COMPLETED", "Tamamlandı"),
                        ],
                        default="ENROLLED",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LearningProgramRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0.0)),
            ],
        ),
    ]
