# Generated by Django 5.2 on 2025-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('course_type', models.CharField(choices=[('POOL', 'Havuz Dersi'), ('FACULTY', 'Fakülte Dersi'), ('DEPARTMENT', 'Bölüm Dersi')], max_length=20, verbose_name='Ders Türü')),
            ],
        ),
    ]
