# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("courses", "0001_initial"),
        ("outcomes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentlearningprogramrelation",
            name="learning_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_component_relations",
                to="outcomes.learningoutcome",
            ),
        ),
        migrations.AddField(
            model_name="componentlearningprogramrelation",
            name="program_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_component_relations",
                to="outcomes.programoutcome",
            ),
        ),
        migrations.AddField(
            model_name="componentlearningrelation",
            name="learning_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="component_relations",
                to="outcomes.learningoutcome",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.level",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="required_for",
                to="courses.course",
                verbose_name="Önşartlı Dersler",
            ),
        ),
    ]
