# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("outcomes", "0002_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="teachers.teacher"
            ),
        ),
        migrations.AddField(
            model_name="courseassessmentcomponent",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="componentlearningrelation",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_relations",
                to="courses.courseassessmentcomponent",
            ),
        ),
        migrations.AddField(
            model_name="componentlearningprogramrelation",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_program_relations",
                to="courses.courseassessmentcomponent",
            ),
        ),
        migrations.AddField(
            model_name="coursegrade",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseassessmentcomponent",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerings",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="instructors",
            field=models.ManyToManyField(
                blank=True, related_name="offerings", to="teachers.teacher"
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="courses.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="courseschedule",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="courses.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="courseattendance",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="courses.courseschedule",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="coursegrade",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="courses.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="courseattendance",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="courses.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="learningprogramrelation",
            name="learning_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_mappings",
                to="outcomes.learningoutcome",
            ),
        ),
        migrations.AddField(
            model_name="learningprogramrelation",
            name="program_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_mappings",
                to="outcomes.programoutcome",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "offering")},
        ),
        migrations.AlterUniqueTogether(
            name="courseattendance",
            unique_together={("enrollment", "schedule")},
        ),
        migrations.AlterUniqueTogether(
            name="learningprogramrelation",
            unique_together={("learning_outcome", "program_outcome")},
        ),
    ]
