# Generated by Django 5.2.8 on 2025-11-12 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("departments", "0004_remove_department_temp_fix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="ects",
            field=models.FloatField(blank=True, null=True, verbose_name="AKTS"),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="required_for",
                to="courses.course",
                verbose_name="Önşartlı Dersler",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="departments.department"
            ),
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("SPRING", "Bahar"),
                            ("FALL", "Güz"),
                            ("SUMMER", "Yaz"),
                            ("WINTER", "Kış"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, help_text="Şube kodu (örn: A, B, 01)", max_length=10
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(default=30, verbose_name="Kontenjan"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "resources",
                    models.TextField(
                        blank=True, help_text="Ders notları / bağlantılar"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="courses.courseoffering",
                    ),
                ),
            ],
            options={
                "ordering": ("week", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Pazartesi"),
                            ("TUE", "Salı"),
                            ("WED", "Çarşamba"),
                            ("THU", "Perşembe"),
                            ("FRI", "Cuma"),
                            ("SAT", "Cumartesi"),
                            ("SUN", "Pazar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("place", models.CharField(blank=True, max_length=200)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="courses.courseoffering",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[
                            ("FACULTY", "Fakülte Hocası"),
                            ("DEPARTMENT", "Bölüm Hocası"),
                        ],
                        default="DEPARTMENT",
                        max_length=20,
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="course_teachers",
                        to="departments.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="instructors",
            field=models.ManyToManyField(
                blank=True, related_name="offerings", to="courses.teacher"
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Kayıtlı"),
                            ("WAITLISTED", "Yedek"),
                            ("DROPPED", "Bırakıldı"),
                            ("COMPLETED", "Tamamlandı"),
                        ],
                        default="ENROLLED",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.courseoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "offering")},
            },
        ),
    ]
