# Generated by Django 5.2.8 on 2025-12-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoffering",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
