# Generated by Django 5.2 on 2025-11-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_faculty_course_ects_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
