# Generated by Django 5.2 on 2025-11-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_faculty'),
        ('teachers', '0002_rename_name_teacher_full_name_remove_teacher_e_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='offerings', to='teachers.teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
