# Generated by Django 5.2.8 on 2025-12-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_courseoffering_is_active"),
        ("hod", "0003_remove_head_head_user_alter_head_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_by_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to="hod.head",
            ),
        ),
    ]
