# Generated by Django 5.2 on 2025-11-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courseoffering_instructors_delete_teacher'),
        ('hod', '0003_remove_head_user_head_head_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hod.head'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20),
        ),
    ]
