# Generated by Django 5.2 on 2025-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_created_by_head_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
