# Generated by Django 5.2 on 2025-11-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ödev (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='attendance_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Devam (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='final_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Final (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='midterm_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Vize (%)'),
        ),
        migrations.CreateModel(
            name='CourseAssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='courses.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
