# Generated by Django 5.2 on 2025-11-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_assignment_weight_course_attendance_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Dönem'),
        ),
    ]
