# Generated by Django 5.2 on 2025-11-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_simpleuser_first_name_simpleuser_last_name'),
        ('courses', '0009_course_semester'),
        ('teachers', '0004_alter_teacher_options_alter_teacher_google_scholar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='resources',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.simpleuser'),
        ),
    ]
