# Generated by Django 5.2 on 2025-11-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_is_active_course_teachers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Katıldı')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.enrollment')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.courseschedule')),
            ],
            options={
                'ordering': ['schedule__day', 'schedule__start_time'],
                'unique_together': {('enrollment', 'schedule')},
            },
        ),
    ]
