# Generated by Django 5.2 on 2025-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courseattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassessmentcomponent',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='assignment_weight',
        ),
        migrations.RemoveField(
            model_name='course',
            name='attendance_weight',
        ),
        migrations.RemoveField(
            model_name='course',
            name='final_weight',
        ),
        migrations.RemoveField(
            model_name='course',
            name='midterm_weight',
        ),
        migrations.RemoveField(
            model_name='courseassessmentcomponent',
            name='name',
        ),
        migrations.AddField(
            model_name='courseassessmentcomponent',
            name='type',
            field=models.CharField(choices=[('MIDTERM', 'Vize'), ('FINAL', 'Final'), ('ASSIGNMENT', 'Ödev'), ('ATTENDANCE', 'Devam'), ('QUIZ', 'Quiz'), ('PROJECT', 'Proje')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
