# Generated by Django 5.2 on 2025-11-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_courseassessmentcomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassessmentcomponent',
            options={'ordering': ['course', 'type']},
        ),
    ]
