# Generated by Django 5.2 on 2025-11-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courseassessmentcomponent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
