# Generated by Django 5.2 on 2025-11-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kodu (ör: PO1)')),
                ('description', models.TextField(verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kodu (ör: LO1)')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_learning_outcomes', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentLearningRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Etki Oranı (%)')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_relations', to='courses.courseassessmentcomponent')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_relations', to='courses.learningoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgramRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Etki Oranı (%)')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_relations', to='courses.learningoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_relations', to='courses.programoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentLearningProgramRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_weight', models.FloatField(default=0, verbose_name='Learning Outcome Oranı (%)')),
                ('program_weight', models.FloatField(default=0, verbose_name='Program Outcome Oranı (%)')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_program_relations', to='courses.courseassessmentcomponent')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_program_relations', to='courses.learningoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_relations', to='courses.programoutcome')),
            ],
        ),
    ]
