# Generated by Django 5.2 on 2025-11-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_programoutcome_learningoutcome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentlearningprogramrelation',
            options={'ordering': ['component', 'learning_outcome'], 'verbose_name': 'Component – Learning & Program Outcome İlişkisi', 'verbose_name_plural': 'Component – Learning & Program Outcome İlişkileri'},
        ),
        migrations.AlterField(
            model_name='componentlearningprogramrelation',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_component_relations', to='courses.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='componentlearningprogramrelation',
            name='learning_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Learning Outcome Katkısı (%)'),
        ),
        migrations.AlterField(
            model_name='componentlearningprogramrelation',
            name='program_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_component_relations', to='courses.programoutcome'),
        ),
        migrations.AlterField(
            model_name='componentlearningprogramrelation',
            name='program_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Program Outcome Katkısı (%)'),
        ),
    ]
