# Generated by Django 5.2 on 2025-11-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_componentlearningprogramrelation_options_and_more'),
        ('outcomes', '0002_learningoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentlearningprogramrelation',
            name='program_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_component_relations', to='outcomes.programoutcome'),
        ),
        migrations.AlterField(
            model_name='learningprogramrelation',
            name='program_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_relations', to='outcomes.programoutcome'),
        ),
        migrations.AlterField(
            model_name='componentlearningprogramrelation',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_component_relations', to='outcomes.learningoutcome'),
        ),
        migrations.DeleteModel(
            name='ProgramOutcome',
        ),
    ]
