# Generated by Django 5.2 on 2025-11-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_componentlearningprogramrelation_program_outcome_and_more'),
        ('outcomes', '0003_alter_programoutcome_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningprogramrelation',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_relations', to='outcomes.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='componentlearningrelation',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_relations', to='outcomes.learningoutcome'),
        ),
        migrations.DeleteModel(
            name='LearningOutcome',
        ),
    ]
