# Generated by Django 5.2 on 2025-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_courseenrollment_coursegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
