# Generated by Django 5.2 on 2025-11-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_courseenrollment_is_active'),
        ('outcomes', '0004_alter_learningoutcome_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningprogramrelation',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_mappings', to='outcomes.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='learningprogramrelation',
            name='program_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_mappings', to='outcomes.programoutcome'),
        ),
        migrations.AlterField(
            model_name='learningprogramrelation',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='learningprogramrelation',
            unique_together={('learning_outcome', 'program_outcome')},
        ),
    ]
