# Generated by Django 5.2.7 on 2025-12-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_alter_learningprogramrelation_learning_outcome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="created_by_head",
        ),
    ]
