# Generated by Django 5.2 on 2025-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('computer', 'Bilgisayar Mühendisliği'), ('biomedical', 'Biyomedikal Mühendisliği')], max_length=20)),
                ('outcome_number', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('program', 'outcome_number')},
            },
        ),
    ]
