# Generated by Django 5.2.8 on 2025-12-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("departments", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="Kodu (ör: LO1)"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "bloom_level",
                    models.CharField(
                        choices=[
                            ("REMEMBER", "Remember"),
                            ("UNDERSTAND", "Understand"),
                            ("APPLY", "Apply"),
                            ("ANALYZE", "Analyze"),
                            ("EVALUATE", "Evaluate"),
                            ("CREATE", "Create"),
                        ],
                        default="REMEMBER",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_outcomes",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_outcomes",
                        to="departments.department",
                        verbose_name="Program / Bölüm",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "code")},
            },
        ),
        migrations.CreateModel(
            name="StudentProgramOutcomeScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("coverage", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outcomes.programoutcome",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_scores",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "program_outcome")},
            },
        ),
    ]
