# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("outcomes", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprogramoutcomescore",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_scores",
                to="students.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programoutcome",
            unique_together={("department", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="studentprogramoutcomescore",
            unique_together={("student", "program_outcome")},
        ),
    ]
