# Generated by Django 5.2 on 2025-11-28 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courseassessmentcomponent_options'),
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='courses.course')),
                ('program_outcomes', models.ManyToManyField(related_name='learning_outcomes', to='outcomes.programoutcome')),
            ],
            options={
                'unique_together': {('course', 'code')},
            },
        ),
    ]
