# Generated by Django 5.2.8 on 2025-12-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outcomes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programoutcome",
            name="code",
            field=models.IntegerField(),
        ),
    ]
