# Generated by Django 5.2.8 on 2025-12-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_initial"),
        ("outcomes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningoutcome",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="bloom_level",
            field=models.CharField(
                choices=[
                    ("REMEMBER", "Remember"),
                    ("UNDERSTAND", "Understand"),
                    ("APPLY", "Apply"),
                    ("ANALYZE", "Analyze"),
                    ("EVALUATE", "Evaluate"),
                    ("CREATE", "Create"),
                ],
                default="REMEMBER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="learningoutcome",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_outcomes",
                to="courses.course",
            ),
        ),
    ]
