# Generated by Django 5.2 on 2025-11-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_departmentcourse_unique_together_and_more'),
        ('outcomes', '0002_learningoutcome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programoutcome',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='departments.department', verbose_name='Program / Bölüm'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='programoutcome',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programoutcome',
            name='outcome_number',
        ),
        migrations.RemoveField(
            model_name='programoutcome',
            name='program',
        ),
    ]
