# Generated by Django 5.2 on 2025-11-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_learningprogramrelation_learning_outcome_and_more'),
        ('departments', '0006_alter_departmentcourse_unique_together_and_more'),
        ('outcomes', '0003_alter_programoutcome_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningoutcome',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Kodu (ör: LO1)'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_learning_outcomes', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterUniqueTogether(
            name='programoutcome',
            unique_together={('department', 'code')},
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='program_outcomes',
        ),
    ]
