# Generated by Django 5.2 on 2025-11-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0004_alter_learningoutcome_unique_together_and_more'),
        ('students', '0007_student_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgramOutcomeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('coverage', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outcomes.programoutcome')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_scores', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'program_outcome')},
            },
        ),
    ]
