# Generated by Django 5.2 on 2025-11-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_simpleuser_password_alter_simpleuser_role'),
        ('courses', '0002_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='accounts.simpleuser'),
        ),
        migrations.AddField(
            model_name='department',
            name='quota',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='DepartmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_departments', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_courses', to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('teacher_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='departments.department')),
            ],
        ),
    ]
