# Generated by Django 5.2 on 2025-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_head_user_department_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='temp_fix',
            field=models.BooleanField(default=False),
        ),
    ]
