# Generated by Django 5.2 on 2025-11-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_temp_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='temp_fix',
        ),
    ]
