# Generated by Django 5.2 on 2025-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_remove_department_temp_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcourse',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20),
        ),
    ]
