# Generated by Django 5.2 on 2025-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_status'),
        ('departments', '0005_departmentcourse_approval_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentcourse',
            unique_together={('department', 'course', 'semester')},
        ),
        migrations.AlterField(
            model_name='departmentstatistic',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Başarı Oranı (%)'),
        ),
        migrations.RemoveField(
            model_name='departmentcourse',
            name='approval_status',
        ),
    ]
