# Generated by Django 5.2.7 on 2025-12-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0006_alter_departmentcourse_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="head_user",
        ),
        migrations.RemoveField(
            model_name="department",
            name="quota",
        ),
    ]
