# Generated by Django 5.2 on 2025-11-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Level',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
