# Generated by Django 5.2 on 2025-11-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_department_level_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='code',
        ),
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
